name: Intiface CLI Build

on: push

jobs:
  build-stable:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Fix ~/.cargo directory permissions
      if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
      run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/
    - name: Update package list
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get -y update
    - name: Install required packages
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get -y install libudev-dev libusb-1.0-0-dev libdbus-1-dev
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('.github/workflows/cache_version') }}
    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('.github/workflows/cache_version') }}
    - name: Rust toolchain fetch
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Formatting check
      continue-on-error: true
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
#    - name: Build Debug
#      run: cargo build
#    - name: Run tests
#      run: cargo test
#    - name: Run doc gen
#      run: cargo doc --no-deps
    - name: Build Release
      run: cargo build --release
    - name: Copy executable (Linux, MacOS)
      if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
      run: |
        mkdir ci-output-release
        cp target/release/intiface-cli ci-output-release/IntifaceCLI
    - name: Copy Info.plist (MacOS)
      if: startsWith(matrix.os, 'macos')
      run: |
        cp src/Info.plist ci-output-release/Info.plist
    - name: Copy executable (Windows)
      if: startsWith(matrix.os, 'windows')
      run: |
        mkdir ci-output-release
        copy target\release\intiface-cli.exe ci-output-release\IntifaceCLI.exe
    - name: Upload artifacts (release)
      uses: actions/upload-artifact@v4
      with:
        name: intiface-cli-rs-${{ runner.os }}-release
        path: ci-output-release
  release:
    name: Release artifacts
    needs: build-stable
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v2
    - name: Download Artifact (Linux)
      uses: actions/download-artifact@v4
      with:
        name: intiface-cli-rs-Linux-release
    - name: Download Artifact (Windows)
      uses: actions/download-artifact@v4
      with:
        name: intiface-cli-rs-Windows-release
    - name: Download Artifact (MacOS)
      uses: actions/download-artifact@v4
      with:
        name: intiface-cli-rs-macOS-release
    - name: Zip executables
      # This follows the naming convention from C# and JS. Use -j to junk the
      # directory structure.
      run: |
        zip -j intiface-cli-rs-linux-x64-Release.zip intiface-cli-rs-Linux-release/IntifaceCLI README.md CHANGELOG.md
        zip -j intiface-cli-rs-win-x64-Release.zip intiface-cli-rs-Windows-release/IntifaceCLI.exe README.md CHANGELOG.md
        zip -j intiface-cli-rs-macos-x64-Release.zip intiface-cli-rs-macOS-release/IntifaceCLI README.md CHANGELOG.md Info.plist
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          intiface-cli-rs-linux-x64-Release.zip
          intiface-cli-rs-win-x64-Release.zip
          intiface-cli-rs-macos-x64-Release.zip
          README.md
          CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
